name: Learning GraphQL | Shruti Kapoor
description: A resource for learning GraphQL
avatar: 'https://avatars.githubusercontent.com/u/2525914?s=60&v=4'
footer-links:
  github: shrutikapoor08/blogs
  rss: null
  twitter: shrutikapoor08
  stackoverflow: null
  youtube: channel/UCbB6Gh3UPI9lUUnPGYMz2ew
  googleplus: null
disqus: null
google_analytics: null
url: null
baseurl: '/'
permalink: '/:title/'
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: ':expanded'
plugins:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - tailwind.config.js
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/